version: '3'
services:
  db-server:
    image: postgres
    environment:
      POSTGRES_USER: "kuma"
      POSTGRES_PASSWORD: "kuma"
      POSTGRES_DB: "kuma"
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - 80:8080
    depends_on:
      - db-server
    environment:
      LANG: "C.UTF-8"
    volumes:
      - .:/go/src/KUMA-server
